apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo"
  annotations:
    github.com/project-slug: qwiklabs-gcp-04-93c32f320821/demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:platform
  lifecycle: experimental
